// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TireControl.Infrastructure.Data;

#nullable disable

namespace TireControl.Infrastructure.Migrations
{
    [DbContext(typeof(TireControlDbContext))]
    partial class TireControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TireControl.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Descricao = "Visualizar usuários",
                            Nome = "Usuario.View"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Descricao = "Criar usuários",
                            Nome = "Usuario.Create"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Descricao = "Alterar usuários",
                            Nome = "Usuario.Update"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Descricao = "Excluir usuários",
                            Nome = "Usuario.Delete"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Descricao = "Visualizar pneus",
                            Nome = "Pneu.View"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Descricao = "Criar pneus",
                            Nome = "Pneu.Create"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Descricao = "Alterar pneus",
                            Nome = "Pneu.Update"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Descricao = "Excluir pneus",
                            Nome = "Pneu.Delete"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Descricao = "Visualizar veículos",
                            Nome = "Veiculo.View"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Descricao = "Criar veículos",
                            Nome = "Veiculo.Create"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Descricao = "Alterar veículos",
                            Nome = "Veiculo.Update"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            Descricao = "Excluir veículos",
                            Nome = "Veiculo.Delete"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            Descricao = "Visualizar relatórios",
                            Nome = "Relatorio.View"
                        });
                });

            modelBuilder.Entity("TireControl.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Descricao = "Acesso administrativo completo ao sistema",
                            Nome = "AdministradorSistema"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Descricao = "Acesso operacional para suporte aos clientes",
                            Nome = "Suporte"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Descricao = "Administrador da empresa cliente",
                            Nome = "AdministradorCliente"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Descricao = "Usuário padrão da empresa cliente",
                            Nome = "UsuarioCliente"
                        });
                });

            modelBuilder.Entity("TireControl.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000013")
                        });
                });

            modelBuilder.Entity("TireControl.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("TireControl.Domain.Entities.UsuarioRole", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("TireControl.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("TireControl.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireControl.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TireControl.Domain.Entities.UsuarioRole", b =>
                {
                    b.HasOne("TireControl.Domain.Entities.Role", "Role")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireControl.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TireControl.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TireControl.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("TireControl.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
